name: Create production promotion pull request

on:
  push:
    branches:
      - 'hotfix/*'  # Trigger for hotfix branches
    workflow_dispatch:

jobs:
  promote-hotfix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          branch: promote-${{ github.ref_name }}
          commit-message: "Promote: Merge changes from ${{ github.ref_name }} to main"
          title: "[Promote] Hotfix: Merge ${{ github.ref_name }} to main (manual merge required)"
          body: "This PR merges branch ${{ github.ref_name }} into main. Please review and merge manually."