name: Create production promotion pull request

on:
  push:
    branches:
      - 'hotfix/*'  # Trigger for hotfix branches
    workflow_dispatch:

jobs:
  promote-hotfix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          branch: promote-${{ github.ref_name }}