name: Create envfile

on:
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate .env
        run: |
          ls
          echo -n ${{ secrets.ENV_FILE }} | base64 --decode > .env
          ls

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run tests
        run: "go test -p 1 -covermode=atomic -coverprofile coverage.out -v ./..."