name: Create envfile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  create-envfile:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Do Something with env files
        run: |
          echo $ENV_FILE | base64 --decode > .env