name: Create envfile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
      - name: Do Something with env files
        run: |
          echo $ENV_FILE | base64 --decode > .env

  setup:
    runs-on: ubuntu-latest
    needs: [create-envfile]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run tests
        run: "go test -p 1 -covermode=atomic -coverprofile coverage.out -v ./..."