name: install-nomad
on: [push]
jobs:
  build:
    runs-on: [self-hosted, x64, linux, klever-pipe]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: node --version
      - run: nomad
