name: Update GitOps

on:
  workflow_call:
    inputs:
      environment:
        description: Target environment
        required: true
        type: string

      image:
        description: Container image
        required: true
        type: string

      image_tag:
        description: Container image tag
        required: true
        type: string

    secrets:
      gitops_token:
        required: true

jobs:
  update:
    name: Update ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v7
        with:
          repository: sibelly/k8s-fundamentals
          token: ${{ secrets.gitops_token }}
          path: k8s-fundamentals

      - name: Update image
        working-directory: k8s-fundamentals
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          IMAGE: ${{ inputs.image }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          cd apps/favorite-go/overlays/${ENVIRONMENT}

          kustomize edit set image \
            ${IMAGE}=${IMAGE}:${IMAGE_TAG}

          echo "Updated ${ENVIRONMENT} to ${IMAGE}:${IMAGE_TAG}"

      - name: Show changes
        working-directory: k8s-fundamentals
        run: git diff

      - name: Commit and push
        working-directory: k8s-fundamentals
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit \
            -m "chore(${ENVIRONMENT}): update favorite-go to ${IMAGE_TAG}"

          git push