
name: learn-environment-variables-secrets
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  - name: Set vars to env
    env:
      VARS_JSON: ${{ toJSON(vars) }}
    run: |
      echo "$VARS_JSON" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> $GITHUB_ENV

  - name: Check env vars
    run: |
      echo "VAR1=$VAR1"
      echo "VAR2=$VAR2"